# Generated by Django 5.2.4 on 2025-12-05 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import public.models.course_model
import public.models.product_model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('cat_img', models.ImageField(default='di_categury.jpg', upload_to='img/categury')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('expiration_date', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product_img', models.ImageField(blank=True, default='di_cook.png', null=True, upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_img', models.ImageField(blank=True, default='dp_image.jpg', null=True, upload_to='img/profile/')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('national_code', models.IntegerField(blank=True, choices=[(1, 'شخصی'), (2, 'شرکتی')], null=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 0 and be exactly 11 digits.', regex='^0\\d{10}$')], verbose_name='Phone number')),
                ('code_posti', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='کد پستی باید دقیقاً ۱۰ رقم باشد و فقط شامل عدد باشد.', regex='^\\d{10}$')], verbose_name='code posti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='banners/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govahiname', models.BooleanField(default=False)),
                ('class_type', models.CharField(choices=[('online', 'آنلاین'), ('in_person', 'حضوری')], max_length=20, verbose_name='نوع کلاس')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('market_description', models.TextField(blank=True, help_text='شرح فرصت\u200cهای شغلی و بازار کار این دوره', null=True, verbose_name='بازار کار')),
                ('syllabus', models.JSONField(default=list, help_text='لیست سرفصل\u200cها به صورت JSON', verbose_name='سرفصل\u200cها')),
                ('prerequisites', models.JSONField(default=list, help_text='لیست پیش\u200cنیازها به صورت JSON', verbose_name='پیش\u200cنیازها')),
                ('acquired_skills', models.JSONField(default=list, help_text='لیست مهارت\u200cهای کسب شده در پایان دوره به صورت JSON', verbose_name='مهارت\u200cهای کسب شده')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('duration', models.IntegerField(verbose_name='مدت دوره (ساعت)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('finaly_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='تخفیف (%)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, default='di_course.png', upload_to=public.models.course_model.course_image_path, verbose_name='تصویر دوره')),
                ('video', models.FileField(blank=True, null=True, upload_to=public.models.course_model.course_image_path, verbose_name='ویدئو معرفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('total_capacity', models.PositiveIntegerField(default=30, verbose_name='ظرفیت کل کلاس')),
                ('available_seats', models.PositiveIntegerField(default=30, verbose_name='تعداد صندلی\u200cهای خالی')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.categury')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField(auto_created=True)),
                ('payment_status', models.CharField(choices=[('در انتظار پرداخت', 'Waiting'), ('پرداخت شده', 'Done')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('در انتظار پرداخت', 'Waiting'), ('پرداخت شده', 'Done')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_created=True)),
                ('status', models.CharField(choices=[('در انتظار پرداخت', 'Waiting'), ('پرداخت شده', 'Done')])),
                ('refrence_number', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=public.models.product_model.product_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.categury')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.tag'),
        ),
    ]
