# Generated by Django 5.2.4 on 2025-11-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categury',
            old_name='img',
            new_name='cat_img',
        ),
    ]
