# Generated by Django 5.2.4 on 2025-10-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='number',
            new_name='phone',
        ),
    ]
