# Generated by Django 5.2.4 on 2025-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_customuser_groups_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_posti',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='code_posti'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='family',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='family'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
    ]
