# Generated by Django 5.2.4 on 2025-11-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='dp_image.jpg', null=True, upload_to=''),
        ),
    ]
