# Generated by Django 5.2.4 on 2025-11-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_product_main_image_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='code_posti',
        ),
    ]
