# Generated by Django 5.2.4 on 2025-11-21 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_remove_customuser_code_posti'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_posti',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='کد پستی باید دقیقاً ۱۰ رقم باشد و فقط شامل عدد باشد.', regex='^\\d{10}$')], verbose_name='code posti'),
        ),
    ]
